#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"
#include "fullRobotTestCommons.h"
#include "fullRobotTestFunctions.h"

void pre_auton(){
	bStopTasksBetweenModes = true;
	bDisplayCompetitionStatusOnLcd = false;
	initialize();
}

task usercontrol(){
	//startTask(autonomous);

	while (true){
		driveOperatorControl(false);
		armOperatorControl(false, false, true);
		mobileGoalOperatorControl(false, false);
		lcdCalibrate();
		delay(LOOPS_DELAY);
	}
}

task autonomous(){
	resetValues();
	clearDebugStream();

	if(mobileGoalIntake.notDone){
		moveMobileGoal(0);
	}
	resetValues();
	writeDebugStreamLine("Extended Mobile Goal Intake");

	if(mobileGoalIntake.notDone){
		moveMobileGoal(1);
	}
	resetValues();
	writeDebugStreamLine("Retracted Mobile Goal Intake");
}
