/*   skillsRobotProgram.c - Draft of program to use with model 6            *
*    Copyright (C) <2017>  Marcos Ricardo Pesante Colón                     *
*                                                                           *
*    This program is free software: you can redistribute it and/or modify   *
*    it under the terms of the GNU General Public License as published by   *
*    the Free Software Foundation, either version 3 of the License, or      *
*    (at your option) any later version.                                    *
*                                                                           *
*    This program is distributed in the hope that it will be useful,        *
*    but WITHOUT ANY WARRANTY; without even the implied warranty of         *
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
*    GNU General Public License for more details.                           *
*                                                                           *
*    You should have received a copy of the GNU General Public License      *
*    along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

#pragma config(Sensor, in1,    armPotL,       sensorPotentiometer)
#pragma config(Sensor, in2,    armPotR,       sensorPotentiometer)
#pragma config(Sensor, dgtl1,  driveEncoderL,  sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  driveEncoderR,  sensorQuadEncoder)
#pragma config(Motor,  port1,           moGoL,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           driveFL,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           driveBL,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           armL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           clawL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           clawR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armR,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           driveBR,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           driveFR,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          moGoR,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"
#include "functions.h"

void pre_auton(){
	bStopTasksBetweenModes = true;
	initialize();
}

task autonomous(){
	while(true){
		move(f,5,100);	//Move base forward 5 inches
		lift(0);	//Move left arm up
		claw(kOpen);	//Open claw
		if(driveDone & armDone & clawDone) break;	//Look if processes are done and break from look if finished
			counter++;
	}

	resetValues();

	while(true){
		move(b,4,100);	//Move base forward 4 inches
		lift(1);	//Move right arm up
		claw(kClose);	//Open claw
		if(driveDone & armDone & clawDone) break;	//Look if processes are done and break from look if finished
			counter++;
	}
}

task usercontrol(){
	while(true){
		driverControl();
	}
}
