#pragma config(Motor,  port1,           DriveBL,       tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           DriveFL,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           DriveFR,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          DriveBR,       tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(true){
		motor[DriveBR] = motor[DriveFR] = vexRT[Ch3] - vexRT[Ch1];
		motor[DriveBL] = motor[DriveFL] = vexRT[Ch3] + vexRT[Ch1];
		wait1Msec(20);
	}
}
