#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"
#include "commons.h"
#include "functions.h"
#include "programmingSkills.h"

void pre_auton(){
	bStopTasksBetweenModes = true;
	bDisplayCompetitionStatusOnLcd = false;
	initialize();
#ifdef META_usingLCD
	do{
		if(bIfiRobotDisabled)	lcdSelect();
		else break;
	}while (!lcdReady);

	//Clear the LCD
	clearLCDLine(0);
	clearLCDLine(1);
	displayLCDCenteredString(0, "     2223-Z     ");    //Output 2223-Z on the screen, signaling that the lcd is done
#endif
}

task usercontrol(){
	while (true){
		driveOperatorControl(false);
		armOperatorControl(false, META_armNotUsePID, true);
		mobileGoalOperatorControl(false, false);
		//lcdCalibrate();
		delay(LOOPS_DELAY);
	}
}

task autonomous(){
	clearDebugStream();
	resetValues();

	while(arm.notDone && claw.notDone){
		move(Forward, 0, 0);
		moveArm(1);
		moveClaw(close, META_clawSpeed);
	}
	resetValues();

	while(arm.notDone){
		move(Forward, 0, 0);
		moveMobileGoal(0);
		moveArm(0);
	}
	resetValues();

	if(currentSideRight){
		switch(currentCode){
		case twentyPointMogo:

			//First forward, move 45 inches
			while(drive.notDone){
				move(Forward, 25, 127);
				moveMobileGoal(0);
			}
			resetValues();

			//First forward, move 45 inches
			while(drive.notDone || mobileGoalIntake.notDone){
				move(Forward, 20, 60);
				moveMobileGoal(0);
			}
			resetValues();

			//FIrst retract, retract Mobile Goal
			while(mobileGoalIntake.notDone){
				moveMobileGoal(1);
			}
			resetValues();

			//First backward, move 35 inches
			while(drive.notDone){
				move(Backward, 35, 50);
			}
			resetValues();

			//First turn, rotate 135 degrees right
			while(drive.notDone){
				move(TurnLeft, 135, 80);
			}
			resetValues();

			//Second forward, move 30 inches forward, parallel to starting bar
			while(drive.notDone){
				move(Forward, 30, 50);
			}
			resetValues();

			//Second turn, rotate 90 degrees right
			while(drive.notDone){
				move(TurnLeft, 90, 75);
			}
			resetValues();

			//Move forward and deposit Mobile Goal
			PID_KIdrive = 1;
			while(drive.notDone || mobileGoalIntake.notDone){
				move(Forward, 22, 100);
				moveMobileGoal(0);
			}
			resetValues();
			PID_KIdrive = 0.5;

			//Move backwards, towards stationary goal
			while(drive.notDone){
				move(Backward, 23, 100);
				moveMobileGoal(1);
			}
			resetValues();

			break;
			break;
		case tenPointMogo:

			while(drive.notDone || mobileGoalIntake.notDone){
				move(Forward, 45, 80);
				moveMobileGoal(0);
			}
			resetValues();

			while(mobileGoalIntake.notDone){
				moveMobileGoal(1);
			}
			resetValues();

			while(drive.notDone){
				move(Backward, 35, 60);
			}
			resetValues();

			while(drive.notDone){
				move(TurnLeft, 145, 75);
			}
			resetValues();

			while(drive.notDone){
				move(Forward, 30, 55);
			}
			resetValues();

			while(drive.notDone){
				move(TurnLeft, 95, 75);
			}
			resetValues();

			while(drive.notDone || mobileGoalIntake.notDone){
				move(Forward, 10, 90);
				moveMobileGoal(0);
			}
			resetValues();

			while(drive.notDone){
				move(Backward, 12, 100);
				moveMobileGoal(1);
			}
			resetValues();

			break;

		case fivePointMogo:

			while(drive.notDone || mobileGoalIntake.notDone){
				move(Forward, 45, 80);
				moveMobileGoal(0);
			}
			resetValues();

			while(mobileGoalIntake.notDone){
				moveMobileGoal(1);
			}
			resetValues();

			while(drive.notDone){
				move(Backward, 30, 60);
			}
			resetValues();

			while(drive.notDone){
				move(TurnLeft, 180, 75);
			}
			resetValues();

			while(mobileGoalIntake.notDone){
				moveMobileGoal(0);
			}
			resetValues();

			while(drive.notDone){
				move(Backward, 6, 127);
				moveMobileGoal(1);
			}
			resetValues();

			break;

		case programmingSkillsCode:
			programmingSkillsAuton();
			break;
		}
	}
	else{
		switch(currentCode){
		case twentyPointMogo:

			//First forward, move 45 inches
			while(drive.notDone){
				move(Forward, 25, 127);
				moveMobileGoal(0);
			}
			resetValues();

			//First forward, move 45 inches
			while(drive.notDone || mobileGoalIntake.notDone){
				move(Forward, 20, 60);
				moveMobileGoal(0);
			}
			resetValues();

			//FIrst retract, retract Mobile Goal
			while(mobileGoalIntake.notDone){
				moveMobileGoal(1);
			}
			resetValues();

			//First backward, move 35 inches
			while(drive.notDone){
				move(Backward, 35, 50);
			}
			resetValues();

			//First turn, rotate 135 degrees right
			while(drive.notDone){
				move(TurnRight, 135, 80);
			}
			resetValues();

			//Second forward, move 30 inches forward, parallel to starting bar
			while(drive.notDone){
				move(Forward, 30, 50);
			}
			resetValues();

			//Second turn, rotate 90 degrees right
			while(drive.notDone){
				move(TurnRight, 90, 75);
			}
			resetValues();

			//Move forward and deposit Mobile Goal
			PID_KIdrive = 1;
			while(drive.notDone || mobileGoalIntake.notDone){
				move(Forward, 22, 100);
				moveMobileGoal(0);
			}
			resetValues();
			PID_KIdrive = 0.5;

			//Move backwards, towards stationary goal
			while(drive.notDone){
				move(Backward, 23, 100);
				moveMobileGoal(1);
			}
			resetValues();

			break;

		case tenPointMogo:

			while(drive.notDone || mobileGoalIntake.notDone){
				move(Forward, 45, 80);
				moveMobileGoal(0);
			}
			resetValues();

			while(mobileGoalIntake.notDone){
				moveMobileGoal(1);
			}
			resetValues();

			while(drive.notDone){
				move(Backward, 35, 60);
			}
			resetValues();

			while(drive.notDone){
				move(TurnRight, 145, 75);
			}
			resetValues();

			while(drive.notDone){
				move(Forward, 30, 55);
			}
			resetValues();

			while(drive.notDone){
				move(TurnRight, 95, 75);
			}
			resetValues();

			while(drive.notDone || mobileGoalIntake.notDone){
				move(Forward, 6, 90);
				moveMobileGoal(0);
			}
			resetValues();

			while(drive.notDone){
				move(Backward, 12, 100);
				moveMobileGoal(1);
			}
			resetValues();

			break;

		case fivePointMogo:

			while(drive.notDone || mobileGoalIntake.notDone){
				move(Forward, 45, 80);
				moveMobileGoal(0);
			}
			resetValues();

			while(mobileGoalIntake.notDone){
				moveMobileGoal(1);
			}
			resetValues();

			while(drive.notDone){
				move(Backward, 30, 60);
			}
			resetValues();

			while(drive.notDone){
				move(TurnRight, 180, 75);
			}
			resetValues();

			while(mobileGoalIntake.notDone){
				moveMobileGoal(0);
			}
			resetValues();

			while(drive.notDone){
				move(Backward, 6, 127);
				moveMobileGoal(1);
			}
			resetValues();

			break;

		case programmingSkillsCode:
			programmingSkillsAuton();
			break;
		}

		resetValues();
		//Program Finishes
	}
}
