#pragma config(Sensor, in1,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in2,    clawPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  RightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           driveLeftFront, tmotorVex393HighSpeed_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           driveLeftBack, tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           liftLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           liftRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           driveRightBack, tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          driveRightFront, tmotorVex393HighSpeed_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
#include "functions.h"

void pre_auton(){
	bStopTasksBetweenModes = true;
	initialize();
}

task autonomous(){
	move(f,360,127);
	lift(50,127);
	intake(10,127);
	hold(kArm,127);
	stop(kArm);
	while(true){
		move(f,360,127);	//Move base forward
		if(SensorValue[LeftEncoder] == 180) baseDone = true;
		lift(90, 127);	//Move arm up
		if(SensorValue[armPot] == 90) armDone = true;
		intake(80,127);	//Open claw
		if(SensorValue[clawPot] == 80) clawDone = true;
		if(baseDone & armDone & clawDone) break;	//Look if processes are done
	}
	resetValues();
}

task usercontrol(){
	//while(true){

	//}
}
