#pragma config(Sensor, in1,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in2,    xBarPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  RightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           driveLeftFront, tmotorVex393TurboSpeed_HBridge, openLoop, driveLeft, encoderPort, dgtl1)
#pragma config(Motor,  port2,           driveLeftBack, tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           liftLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           xBarLeft,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           xBarRight,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           liftRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           driveRightBack, tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          driveRightFront, tmotorVex393TurboSpeed_HBridge, openLoop, reversed, driveRight, encoderPort, dgtl3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"
#include "functions.h"

void pre_auton(){
	bStopTasksBetweenModes = true;
	initialize();
}

task autonomous(){
	move(f,360,127);
	lift(47,127);
	intake(10,127);
	hold(kArm,127);
	stop(kArm);
	getSensor(kEncoderLeft);
	while(true){
		move(f,360,127);	//Move base forward
		lift(90, 127);	//Move arm up
		intake(80,127);	//Open claw
		if(baseDone & armDone & clawDone) break;	//Look if processes are done and break from look if finished
	}
	resetValues();
}

task usercontrol(){
	while(true){
		driverControl();
	}
}
