#pragma config(Sensor, in1,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in2,    clawPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  RightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           baseLeftFront, tmotorVex393HighSpeed_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           baseLeftBack,  tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           armLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           armRight,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           baseRightBack, tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port10,          baseRightFront, tmotorVex393HighSpeed_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
#include "functions.h"



void pre_auton(){
	bStopTasksBetweenModes = true;
	initialize();
}

task autonomous(){
	move(f,360,127);
	lift(50,127);
	intake(10,127);
	hold(kArm,127);
	stop(kArm);
	/*while(true){
	baseF(180);	//Move base forward
	if(SensorValue[EncoderLeft == 180]) baseDone = true;
	armUp(90);	//Move arm up
	if(SensorValue[armPot == 90]) armDone = true;
	clawOpen(80);	//Open claw
	if(SensorValue[clawPot == 80]) clawDone = true;
	if(baseDone & armDone & clawDone) break;	//Look if processes are done
	}*/
}

task usercontrol(){
	while(true){

	}
}
