#pragma config(Motor,  port1,           MOTOR_mogo,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           MOTOR_driveLB, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           MOTOR_liftL,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           MOTOR_driveLF, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           MOTOR_4L,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           MOTOR_4R,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           MOTOR_driveRF, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           MOTOR_liftR,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           MOTOR_driveRB, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          MOTOR_roller,  tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"



void pre_auton(){

	bStopTasksBetweenModes = true;

}


task autonomous(){
	AutonomousCodePlaceholderForTesting();
}

task usercontrol(){
	while (true){
		motor[MOTOR_driveLB] = motor[MOTOR_driveLF] = (vexRT[Ch3] + vexRT[Ch1]);
		motor[MOTOR_driveRB] = motor[MOTOR_driveRF] = (vexRT[Ch3] - vexRT[Ch1]);

		motor[MOTOR_liftL] = motor[MOTOR_liftR] = vexRT[Ch2];

		if (vexRT[Btn5U] == 1)	motor[MOTOR_4L] = motor[MOTOR_4R] = 127;
		else if (vexRT[Btn5D] == 1)	motor[MOTOR_4L] = motor[MOTOR_4R] = -127;
		else	motor[MOTOR_4L] = 0;

		if (vexRT[Btn6U] == 1)	motor[MOTOR_roller] = 127;
		else if (vexRT[Btn6D] == 1)	motor[MOTOR_roller] = -127;
		else	motor[MOTOR_roller] = 0;

		if (vexRT[Btn7U] == 1)	motor[MOTOR_mogo] = 127;
		else if (vexRT[Btn7D] == 1)	motor[MOTOR_mogo] = -127;
		else	motor[MOTOR_mogo] = 0;
	}
}
